spring:
  main:
    banner-mode: 'off'
  data:
    mongodb:
      database: cityDirectory
      port: 27017
      host: localhost

server:
  port: 9090

mongock:
  runner-type: "ApplicationRunner"
  change-logs-scan-package:
    - lesson41.migration