spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/db?serverTimezone=Europe/Moscow&useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: db
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    rest:
      base-path: api

server:
  port: 8085

module:
  basic:
    url: http://localhost:8080/directory

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      build:
        enabled: true
      env:
        enabled: true
      git:
        mode: "full"
